### ISSUE TITLE
Zotero 6 compatibility

### ISSUE THREAD

**Issue by retorquere** [retorquere/zotero-asreview#1]

**Comment by retorquere** [comment]
@Jack-613 0.0.1.4 only matches on DOI.

**Comment by Jack-613** [comment]
Thx !!!

Emiliano Heyns ***@***.***> schrieb am Mo., 25. Okt. 2021,
21:28:

**Comment by retorquere** [comment]
If it works to your satisfaction, I can release it. The build URLs above will expire in a week or so.

**Comment by Jack-613** [comment]
Dear Emile,

Works perfectly, very good !

Thank you so much !

Best Jakob

**Comment by retorquere** [comment]
OK, release 1.0.0 has been published

**Comment by Jack-613** [comment]
Dear Emile,

thank you for your quick reply. 

I have followed your advice and uninstalled plugins.

It was probably the Asreview plugin, when it was uninstalled the entries were visible again. 

Apparently it is not compatible with this new Zotero version (6).

Is there a quick way to reinstall zotero 5 for example and block the automatic update to zotero 6 ?

Best regards
Jakob

**Comment by retorquere** [comment]
Not really, but I can make the asreview plugin compatible in a few hours.

**Comment by retorquere** [comment]
It was already supposed to be compatible with Z6. I'll look into it in more depth later tonight

**Comment by retorquere** [comment]
BTW, please open new issues for, well, new issues.

**Comment by retorquere** [comment]
Do you have a DOI for which asreview should retrieve data?

**Comment by retorquere** [comment]
try build 12

**Comment by Jack-613** [comment]
Perfect :-) is working again THX !

**Comment by retorquere** [comment]
Super. I've put out a new release. For any other things, please open a new issue.
